---
- name: Install upstream deb
  ansible.builtin.apt:
    deb: "{{ amazon_ssm_agent_package }}"
    state: present
  tags:
    - amazon-ssm-agent

- name: Start agent service
  when:
    - not ansible_check_mode
  ansible.builtin.systemd:
    name: amazon-ssm-agent
    state: started
    daemon_reload: true
    masked: false
    enabled: true
  tags:
    - amazon-ssm-agent

...
