---
name: readme

"on":
    workflow_dispatch:
    push:
    branches:
        - master

jobs:
    readme:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'pascalrimann'

    steps:
        - name: Checkout source
          uses: actions/checkout@v4

        - name: Generate readme
          uses: actionhippie/ansible-doctor@v5
          with:
              force: true
              verbose: true

        - name: Commit changes
          uses: EndBug/add-and-commit@v9
          with:
            author_name: GitHub Actions
            author_email: pascal.rimann@yahoo.de
            add: README.md
            message: "docs: automated readme update [skip ci]"
            push: true
            commit: --signoff

...