---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: readme

"on":
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  readme:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'cloudpunks'

    steps:
      - name: Generate token
        id: token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          app-id: ${{ secrets.TOKEN_EXCHANGE_APP }}
          private-key: ${{ secrets.TOKEN_EXCHANGE_KEY }}
          permission-contents: write

      - name: Checkout source
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          token: ${{ steps.token.outputs.token }}

      - name: Generate readme
        uses: actionhippie/ansible-doctor@40ccde6609c522323835343bfd4a8eb736b9edef # v6
        with:
          force: true
          verbose: true

      - name: Source rebase
        run: git pull --autostash --rebase

      - name: Commit changes
        uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10
        with:
          author_name: GitHub Actions
          author_email: github@cloudpunks.de
          add: README.md
          message: "docs: automated readme update [skip ci]"
          push: true
          commit: --signoff

...
