---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: readme

"on":
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  readme:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'cloudpunks'

    steps:
      - name: Generate token
        id: token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        with:
          app-id: ${{ secrets.TOKEN_EXCHANGE_APP }}
          private-key: ${{ secrets.TOKEN_EXCHANGE_KEY }}
          permission-contents: write

      - name: Checkout source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          token: ${{ steps.token.outputs.token }}

      - name: Generate readme
        uses: actionhippie/ansible-doctor@eed1d139e5afbda9822c8e7e5cf23377871c91cd # v6
        with:
          force: true
          verbose: true

      - name: Source rebase
        run: git pull --autostash --rebase

      - name: Commit changes
        uses: EndBug/add-and-commit@290ea2c423ad77ca9c62ae0f5b224379612c0321 # v10
        with:
          author_name: GitHub Actions
          author_email: github@cloudpunks.de
          add: README.md
          message: "docs: automated readme update [skip ci]"
          push: true
          commit: --signoff

...
