---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: galaxy

"on":
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*

permissions:
  contents: read

jobs:
  galaxy:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'cloudpunks'

    steps:
      - name: Checkout source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Galaxy upload
        uses: actionhippie/ansible-galaxy@2e1b49fbc944777a336bee7a2041e923ca13fd51 # v1
        with:
          token: ${{ secrets.GALAXY_TOKEN }}

...
