---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: galaxy

"on":
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*

permissions:
  contents: read

jobs:
  galaxy:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'cloudpunks'

    steps:
      - name: Checkout source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Galaxy upload
        uses: actionhippie/ansible-galaxy@185f311ac6b40d0d87cb8f7b3e35a8da90f3b526 # v1
        with:
          token: ${{ secrets.GALAXY_TOKEN }}

...
