---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: general

"on":
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'cloudpunks'

    steps:
      - name: Checkout source
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Role linting
        uses: ansible/ansible-lint@53b1143167f46793535d4719c94727ea5e91cfb6 # main
        with:
          requirements_file: requirements.yml

  testing:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'cloudpunks'

    strategy:
      fail-fast: false

      matrix:
        scenario:
          - default

    steps:
      - name: Drop hosted
        run: rm -rf /opt/hostedtoolcache/Python

      - name: Checkout source
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip3 install docker pytest-testinfra ansible molecule molecule-plugins[docker]

      - name: Molecule tests
        run: molecule test --scenario-name ${{ matrix.scenario }}
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"

...
